# Initial version generated by chatGPT on 20/05/2023
import json
from jsonschema import validate
from jsonschema.exceptions import ValidationError

def validate_yaml_schema(config):
    with open("../schema/docpic.json", "r") as file:
        schema = json.load(file)



    # Validate the YAML config against the schema
    try:
        validate(instance=config, schema=schema)
        return True
    except ValidationError as e:
        print("Invalid Yaml: " + str(e))
        return False

