# Initial conditions: a pointer to a file which carries out a common task, such as logging in.
# Note that for the below yaml to work, you must set up your environment variables.
# initial-conditions: "../yaml_and_markup/login.dp.yaml"

# Or use initial URL - if no initial conditions are required
url: 'https://tutorialsninja.com/demo/'

# Webdriver options as per https://peter.sh/experiments/chromium-command-line-switches/
webdriver-options:
  headless: false
  window-size: "1280,900"

# Define the steps that will be carried out by the script, and then take the screenshot.
steps:
  - type: identify
    var: search
    using: name
    selector: "search"
  - type: enter-text
    target:
      type: var-ref
      var-name: search
    value: "samsung"
  - type: click
    target:
      type: identify
      var: ~
      using: css
      selector: "i.fa.fa-search"
  - type: identify
    var: sortdropdown
    using: id
    selector: "input-sort"
  - type: click
    target:
      type: var-ref
      var-name: sortdropdown
  - type: select
    target:
      type: var-ref
      var-name: sortdropdown
    value: "Rating (Highest)"
  - type: click
    target:
      type: identify
      var: ~
      using: link
      selector: "Samsung Galaxy Tab 10.1"
  - type: identify
    var: quantity
    using: id
    selector: "input-quantity"
  - type: clear
    target:
      type: var-ref
      var-name: quantity
  - type: enter-text
    target:
      type: var-ref
      var-name: quantity
    value: "2"
  - type: click
    target:
      type: identify
      var: ~
      using: id
      selector: "button-cart"
  - type: wait
    value: 3
  - type: identify
    var: ~
    using: css
    selector: "div.alert.alert-success.alert-dismissible"
  - type: docpic # docpic could be extended, I would like this to be able to focus on a particular element.
    outfile: "test.png" # Ideally there would be a post-processing step that can highlight elements of interest or add text or both.
    alt-text: "A test image"

